src/objects/employe__c.object
<CustomObject>
    <fields>
        <fullName>Store__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Store</label>
        <referenceTo>Store__c</referenceTo>
        <relationshipLabel>employes</relationshipLabel>
        <relationshipName>employes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>description__c</fullName>
        <formula>Store__r.StoreName__c  + &apos;   #   &apos; + TEXT(Store__r.StoreType__c)</formula>
        <label>description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>new__c</fullName>
        <formula>HYPERLINK(&quot;https://na9.salesforce.com/001/e?retURL=%2F001%2Fo&quot;, &quot;Create a New Account&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>new</label>
        <type>Text</type>
    </fields>
    <label>employe</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>employ</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>employes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Store__c.object
<CustomObject>
    <description>This is a generic template for Custom Object. With this
		template, you may adjust the default elements and values and add new
		elements and values.</description>
    <fields>
        <fullName>StoreName__c</fullName>
        <label>StoreName</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StoreType__c</fullName>
        <label>StoreType</label>
        <picklist>
            <picklistValues>
                <fullName>CoffeeStore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RetailStore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>StreetStore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>inHouseStore</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>emailAdress__c</fullName>
        <description>the Email</description>
        <label>emailAdress</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StarbucksController.cls
/**
*/


global with sharing class StarbucksController {

	public List <Store__c>  storeList { get;set;}
	public list <employe__c> employees {get;set;}
	
	//public  Store__c storeList {get;private set;}
	public Store__c store ;
	public List <StoreWrapper> stores {get;set;}
	public String storeMsg {get;set;}
	public StarbucksController () {
		
		stores = new List<StoreWrapper>();
		List <Store__c> records = [ SELECT Id,StoreName__c, StoreType__c, emailAdress__c FROM Store__c LIMIT 2];
		storeList= [ SELECT Id,StoreName__c, StoreType__c,emailAdress__c FROM Store__c LIMIT 2];
		employees = [Select e.new__c, e.description__c, e.Store__c, e.Name, e.Id From employe__c e  LIMIT 10];
		 for (Store__c record : records) {
		 	
		 	System.debug('id'+record.id );
		 	stores.add ( new StoreWrapper(record));
		 }
	}
	
	public Pagereference printMsg() {
		
		 for (StoreWrapper wrapper : stores) {
		 	if (wrapper.selected) {
			System.debug(wrapper.data.Id);
		 	}
		 }
		 
		return null;
	}

	public Pagereference refreshStore() {	 
	
		return null;
	}
	
		public Pagereference edit() {	 
	
		return null;
	}
	
	public Pagereference save() {		
		
		//for (StoreWrapper store : stores) {
		 	update storeList;
		 //	}
		 	return null;
		 }	 	
		
	public Pagereference saveSingle() {		
		
		store = [ SELECT Id,StoreName__c, StoreType__c, emailAdress__c FROM Store__c LIMIT 1];
		 	update store;
		 
		 	return Apexpages.currentPage();
		 }	 	
		
class StoreWrapper {
	public Store__c data {get;  set;}
	public Boolean selected {get;set;}
	public StoreWrapper (Store__c store) {
		this.data=store;
		
		this.selected = false;
		
	}
}
@RemoteAction
    global static String getStoreJson(Id id) //Need to define as a remote action as we will be calling this through javascript
      {
        Store__c lStore = [SELECT Id, Name, StoreName__c FROM Store__c where Id=:id];
        String JSONString = JSON.serialize(lStore);//This is how we can serailize our response into JSON format
        return '{\"Records\":' +JSONString+', \"error\": \"null\", \"status\":\"SUCCESS\", \"count\":\"' + 1 + '\" }';
    }
}