src/objects/myObject__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Call_Status__c</fullName>
        <label>Call_Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RefreshCount__c</fullName>
        <label>RefreshCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>myObject</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>myObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MyObjectExtentsion.cls
public with sharing class MyObjectExtentsion {
    private string objectID = '';
    public string URLForPage{get;set;}
    
        //Constructor
    public MyObjectExtentsion(ApexPages.StandardController stdController) {
           URLForPage = ApexPages.currentPage().getHeaders().get('Host');
           objectID =  stdController.getId();      
        }
    
    //action="{!incrementRefreshCounter}" Put this in the Visualforce Page
        public void incrementRefreshCounter(){
           myObject__c myObject;
           myObject = [Select ID, RefreshCount__c, Call_Status__c
                    From myObject__c
                    Where ID = :objectID];
           if (myObject.Call_Status__c == 'In Progress' || myObject.Call_Status__c == 'Timed Out'){
            myObject.RefreshCount__c += 1;
            if (myObject.RefreshCount__c > 5){
                myObject.Call_Status__c = 'Timed Out';
            }
            update myObject;
           }       
       }   
}