src/objects/Store__c.object
<CustomObject>
    <description>This is a generic template for Custom Object. With this
		template, you may adjust the default elements and values and add new
		elements and values.</description>
    <fields>
        <fullName>StoreName__c</fullName>
        <label>StoreName</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StoreType__c</fullName>
        <label>StoreType</label>
        <picklist>
            <picklistValues>
                <fullName>CoffeeStore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RetailStore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>StreetStore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>inHouseStore</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StarbuckBatchStateful.cls
global  class StarbuckBatchStateful implements Database.Batchable<SObject>, Database.Stateful {
 
 	Integer cnt=0;
	global Database.Querylocator start (Database.Batchablecontext context) {
		System.debug('start: ' +cnt);
		return Database.getQueryLocator([ select StoreName__c, StoreType__c from Store__c 
		ORDER BY StoreName__c]);
		
	}
	
	global void execute (Database.Batchablecontext context, List<SObject> scope) {
	
	System.debug('execute:' +cnt);
		
		for (SObject rec : scope ) {
			Store__c store = (Store__c)rec;
			System.debug(cnt+ ' Store'+ store.StoreName__c);
		}
	}
	
	global void finish (Database.Batchablecontext context) {
		System.debug('finish:' +cnt);
	}
}