src/objects/Store__c.object
<CustomObject>
    <description>This is a generic template for Custom Object. With this
		template, you may adjust the default elements and values and add new
		elements and values.</description>
    <fields>
        <fullName>StoreName__c</fullName>
        <label>StoreName</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StarbucksIterableBatch.cls
global class StarbucksIterableBatch  implements Database.Batchable<Store__c> {
 
	global Iterable<Store__c>  start (Database.Batchablecontext context) {
		System.debug('start');
		return new StoreIterable();
		
	}
	
	global void execute (Database.Batchablecontext context, List<SObject> scope) {
	
	System.debug('execute');
		
		for (SObject rec : scope ) {
			Store__c store = (Store__c)rec;
			System.debug('Store'+ store.StoreName__c);
		}
	}
	
	global void finish (Database.Batchablecontext context) {
		System.debug('finish');
	}
}