src/objects/Store__c.object
<CustomObject>
    <description>This is a generic template for Custom Object. With this
		template, you may adjust the default elements and values and add new
		elements and values.</description>
    <fields>
        <fullName>StoreType__c</fullName>
        <label>StoreType</label>
        <picklist>
            <picklistValues>
                <fullName>CoffeeStore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RetailStore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>StreetStore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>inHouseStore</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestService.cls
@RestResource(urlMapping='/Starbucks/*')
	
global with sharing class TestService {




    @HttpGet
    global static Store__c doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String id = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        Store__c result = [SELECT Name, Id,Store__c.StoreType__c  FROM Store__c WHERE Id = :id];
        return result;
    }
   /*   
  public static xmldom geocode( string addr ) { 
    HttpRequest req = new HttpRequest();   
    string url = GoogleGeoCode.serviceUrl + '&output=xml&q=' + EncodingUtil.urlEncode(addr,'UTF-8');
    system.debug ( 'url is ' +url );
    req.setEndpoint( url );
    req.setMethod('GET');
      
    xmldom dom = null;
    try {
        Http http = new Http();
        HttpResponse response = http.send(req);    
        if (response.getStatusCode() != 200 ) {
            dumpResponse ( response);
        } else {
            dom = new xmldom( response.getBody() );
        } 
    } catch( System.Exception e) {
        System.debug('ERROR: '+ e);
    }  
    
    if ( googleGeoCode.debug > 0 && dom != null ) { 
        dom.dumpAll(); 
    } 
    return dom;
    }
    */
 
}