src/objects/Store__c.object
<CustomObject>
    <description>This is a generic template for Custom Object. With this
		template, you may adjust the default elements and values and add new
		elements and values.</description>
    <fields>
        <fullName>StoreName__c</fullName>
        <label>StoreName</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StoreIterable.cls
global class StoreIterable implements Iterator<Store__c>, Iterable<Store__c> {

	List<Store__c> stores {get;set;}
	Integer i;
	
	public StoreIterable() {
		stores = [Select StoreName__c From Store__c ORDER BY StoreName__c];
		i=0;
	}
	
	global Boolean hasNext() {
		if ( i >= stores.size() ) {
			return false;
		} else {
			return true;
		}
	}
	global Store__c next() {
		i++;
		return stores[i-1];
	}
	
	global Iterator<Store__c> Iterator() {
		return this;
	}
}